### PR TITLE
moved contents from scripts/disvis to disvis/disvis.py to streamline …

### PR DESCRIPTION
**Pull request by schaarj**
…with powerfit routine

### CODE REVIEW

**Comment by mtrellet** [comment]
Gydo, this is linked to my previous email, we found a workaround that kind of simplify the whole code and make it work nicely in the same way that powerfit works ;)

**Comment by latrocinia** [comment]
OK, but I prefer it better if the script of disvis is not in disvis.py. It
a bit weird with the naming then, but else merging this with the devel
version with ambiguous restraints in the near future is going to be
annoying. So for now I will move it to a script.py or main.py file in the
disvis package.

2016-11-03 9:30 GMT-04:00 Mikael Trellet notifications@github.com:

**Comment by schaarj** [comment]
sure as long as we can use `from disvis import something` which would give access to the main routine from within python with `something.main()`  that would be fine.

**Comment by latrocinia** [comment]
It is done. The script has been moved to main.py.

2016-11-03 12:26 GMT-04:00 Joerg Schaarschmidt notifications@github.com:

**Pull request closed without merging**
