### PR TITLE
change element to title case to match keys in elements.py

### PR DESCRIPTION
**Pull request by schaarj**
Fix input handling as elements are upper case in input files and titlecase in elements.py

### CODE REVIEW

**Comment by schaarj** [comment]
just on a side note the current code just takes the first letter from the name if the element column is missing, which might give issues especially for 2 character elements where no element for the first letter exists

**Comment by latrocinia** [comment]
This happens only I guess with HETATMs. It's pretty insane if the element column is missing for those. 

However, if you want to be even more forgiving, you can work around that. Do take into account they may carry a charge in the name, so taking the first two letters will probably also fail in the long run.

**Review by latrocinia — APPROVED** [review]

**Comment by amjjbonvin** [comment]
If the PDB is not coming from the PDB database most likely it won't have the element column...

=================================
 Prof. A.M.J.J. Bonvin | Faculty of Science
 Utrecht University | bonvinlab.org 
 a.m.j.j.bonvin@uu.nl | T: +31 30 2533859 
=================================

**Comment by JoaoRodrigues** [comment]
Have a look at Biopython's element guessing function. Not perfect for
HETATM (at all actually) but works well for most of the others.

2016-12-15 11:47 GMT-08:00 Alexandre Bonvin <notifications@github.com>:

**Comment by schaarj** [comment]
I can take a look to default to Carbon if the element type is not determinable but adding Biopython to the current parsing seems a little excessive for this PR. From what I understand the element is only used for the vdw radii to determine the clashing and interacting volume right?  So just making sure it doesn't fail with a "cryptic" error message in connection with a slightly off volume seems fair to me.

**Comment by JoaoRodrigues** [comment]
I meant just have a look at how the elements are parsed from the atom name.
Not copy the entire parser, that's indeed overkill.

A qui, 15/12/2016, 12:55, Joerg Schaarschmidt <notifications@github.com>
escreveu:

**Comment by schaarj** [comment]
Added a small parsing function somewhat different than the Biopython one but should be robust enough. 
Issues/shortcomings (mostly related to the ambiguous CA):
* doesn't recognise 2 character elements in ATOM entries
* if a modified aa is using HETATM, the CA will be interpreted as Ca (which has an associated vdw of 0.0 in elements.py)

**Comment by JoaoRodrigues** [comment]
The convention is, for inorganic compounds, the atoms (like Ca in case of
calcium) should be displaced one character to the left. I think the
Biopython parser takes that into account. It fails for other cases where
there is really no solution, like Helium or Hydrogens with an E subname
(HE) and a number, like HE1.. This is where it gets messy.​ But if you
think the problem is CAs, then it should be fine the way it is.

**Comment by schaarj** [comment]
@JoaoRodrigues  I noticed that this seemed to be the convention but was wondering wether if the element column is missing these standards would be followed.
 Changed the code nevertheless and now CA properly positioned will not be parsed as Ca in HETATM
fields. This should be the final version. If somebody with write access could **merge the pull request** so I can update the docker images for the server, I would appreciate it!

**Pull request merged**
