### PR TITLE
fix improper atom selection syntax of pdb object

### PR DESCRIPTION
**Pull request by schaarj**
should fix issue #8

### CODE REVIEW

**Comment by latrocinia** [comment]
The PowerFit implementation solves another problem with the != operator in the selection. So maybe better to copy it from there.

**Comment by schaarj** [comment]
Sure I can apush another commit adding that part as well, wasn't sure if that operator was even used in DisVis. What about the `isinstance(values, Iterable)` vs `isinstance (values, Sequence)`  the datatype used in the powerfit implementation?

**Comment by latrocinia** [comment]
It's not used, but might as well add it in for completeness sake. 

I was thinking of that, and it doesn't really matter I think. The Iterable is a superset of the Sequence, so both are fine.

**Comment by schaarj** [comment]
added the != operator, not sure about the implications of adding the Sequence datatype unless you think it's safe and relevant we can go for it though

**Comment by latrocinia** [comment]
Looks good to me, if it runs properly, this can be merged on my part.

**Comment by schaarj** [comment]
will test and do so later than!

**Comment by schaarj** [comment]
thanks for looking into this

**Pull request merged**
